# Generated by Django 3.2.7 on 2022-07-17 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('arrondissement', models.CharField(max_length=55)),
                ('nbchambre', models.IntegerField(null=True)),
                ('nbsalon', models.IntegerField(null=True)),
                ('nbcuisine', models.IntegerField(null=True)),
                ('nbdouche', models.IntegerField(null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='camhouse/house/')),
                ('sommes', models.IntegerField(null=True)),
                ('etat', models.IntegerField(null=True)),
                ('nom', models.CharField(max_length=50, null=True)),
                ('nbinfrastructure', models.IntegerField(null=True)),
                ('lat', models.FloatField(null=True)),
                ('lng', models.FloatField(null=True)),
                ('date', models.FloatField(null=True)),
                ('pay', models.CharField(max_length=55, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camhouse.category')),
            ],
        ),
        migrations.CreateModel(
            name='Insigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Typecomposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Typepayement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proprietaire', models.IntegerField()),
                ('date', models.FloatField()),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camhouse.house')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.IntegerField()),
                ('day', models.FloatField()),
                ('pay', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proprietaire', models.IntegerField()),
                ('date', models.FloatField()),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camhouse.house')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.FloatField()),
                ('proprietaire', models.CharField(max_length=20, null=True)),
                ('phonenumber', models.IntegerField(null=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camhouse.house')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='camhouse/infrastucture/')),
                ('imageUn', models.ImageField(upload_to='camhouse/infrastuctureUn/')),
                ('imageDeux', models.ImageField(upload_to='camhouse/infrastuctureDeux/')),
                ('description', models.TextField()),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camhouse.house')),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camhouse.typepayement'),
        ),
        migrations.AddField(
            model_name='house',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('day', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compte', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='camhouse/chambre/')),
                ('imageUn', models.ImageField(null=True, upload_to='camhouse/chambreUn/')),
                ('imageDeux', models.ImageField(null=True, upload_to='camhouse/chambreDeux/')),
                ('longeur', models.FloatField()),
                ('largeur', models.FloatField()),
                ('hauteur', models.FloatField()),
                ('montant', models.IntegerField(null=True)),
                ('statut', models.CharField(max_length=15)),
                ('numbre', models.IntegerField()),
                ('description', models.TextField()),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camhouse.house')),
                ('insigne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camhouse.insigne')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camhouse.typecomposition')),
            ],
        ),
        migrations.CreateModel(
            name='ChambreUniv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insigne', models.CharField(max_length=10)),
                ('date', models.FloatField()),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camhouse.composition')),
            ],
        ),
    ]
