# Generated by Django 3.2.7 on 2022-07-22 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camhouse', '0004_reservationuniv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationuniv',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camhouse.chambreuniv'),
        ),
    ]
