# Generated by Django 3.2.7 on 2022-07-22 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camhouse', '0005_alter_reservationuniv_house'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservationuniv',
            old_name='house',
            new_name='chambre',
        ),
    ]
