# Generated by Django 3.2.7 on 2022-07-26 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('camhouse', '0006_rename_house_reservationuniv_chambre'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccupationUniv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proprietaire', models.IntegerField()),
                ('date', models.FloatField()),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camhouse.chambreuniv')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
