# Generated by Django 3.2.5 on 2022-08-26 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camhouse', '0008_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='camhouse.house'),
        ),
    ]
