# Generated by Django 3.2.5 on 2022-09-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camhouse', '0009_message_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sms',
            field=models.TextField(null=True),
        ),
    ]
